Map and Content
Chamber6821/berega-map pull request #21
Opened 2024-08-14 12:50 UTC by vladvg8

2024-08-14 13:03 UTC, vladvg8 commented
Убрал из Building поле API, убрал из useFilter его, оставил только для отображения и в поле Filter, чтоб через Content обращаться с ним из другого компонента. Убрал из Content пропс building, теперь в зависимости от того чтоб выбрано в фильтрах в поле API будет fetch нужных объектов. Так же накинул в Map еще один useeffect, который постоянно отдает новый центр на карте если он изменяется. Через f12 можешь посмотреть, он в консоли вылетает

2024-08-14 13:20 UTC, Chamber6821 commented
`API` и все остальные аббревиатуры должны записываться как просто слово, т.е. `Api`

2024-08-14 13:38 UTC, Chamber6821 requested changes

2024-08-14 13:38 UTC, Chamber6821 commented on app/Content.tsx
> +  useEffect(() => {
В итоговом коде не должно быть принтов для отладки

2024-08-14 13:38 UTC, Chamber6821 commented on app/filters/FiltersPopup.tsx
> +  const [[API, setAPI], APIInput] = useVariantInput([...FilterAPIes], {required: true})
В этом контентом случае можно обойтись функционально без `required` одним пунктом условно `Больше данных`. В такой настройке input будет работать как тумблер, однако визуально будет не очевиден для пользователя, но это не проблема корректно этого input'а. Если нужно более понятное отделение для пользователя, то стоит написать новую объекту, например `useSwitch`

2024-08-14 13:38 UTC, Chamber6821 commented on app/filters/FiltersPopup.tsx
> -const useVariantInput = <T extends string,>(variants: T[]): [State<T[]>, React.ReactElement] => {
Не стоит дополнять функционал существующих объектов, лучше написать новую. Ниже написал подробнее

2024-08-14 13:38 UTC, Chamber6821 commented on app/Content.tsx
> +    if(filters.API.includes('Встроенное')) {
API в CamelCase

2024-08-14 13:38 UTC, Chamber6821 commented on app/filters/FiltersPopup.tsx
> +import { FilterFrames, FilterGroups, FilterRooms, FilterStatuses, Range, useFilters, FilterAPIes } from "./useFilters";
API в CamelCase

2024-08-14 13:38 UTC, Chamber6821 commented on app/filters/FiltersPopup.tsx
> +  const [[API, setAPI], APIInput] = useVariantInput([...FilterAPIes], {required: true})
API в CamelCase

2024-08-14 13:38 UTC, Chamber6821 commented on app/filters/FiltersPopup.tsx
> +      API
API в CamelCase

2024-08-14 13:38 UTC, Chamber6821 commented on app/filters/FiltersPopup.tsx
> +    setAPI(filters.API)
API в CamelCase

2024-08-14 13:38 UTC, Chamber6821 commented on app/filters/useFilters.ts
> +export type FilterAPI = typeof FilterAPIes[number]
API в CamelCase

2024-08-14 13:38 UTC, Chamber6821 commented on app/filters/useFilters.ts
> +  API: FilterAPI[]
API в CamelCase

2024-08-14 13:38 UTC, Chamber6821 commented on app/filters/useFilters.ts
> +  API: ['Встроенное'],
API в CamelCase

2024-08-14 13:38 UTC, Chamber6821 commented on app/filters/useFilters.ts
> -
Разделительная строка должна остаться здесь

2024-08-14 13:38 UTC, Chamber6821 commented on app/map/Map.tsx
> +                                { center: [number, number], zoom: number, buildings: Building[], onClickInfo?: () => void, onMapMove?: (center: [number, number]) => void }) {
Тип получается слишком длинным, лучше написать каждое поле на отдельной строке

2024-08-15 11:33 UTC, vladvg8 commented
![image](https://github.com/user-attachments/assets/6a80b3d0-ff0c-45d5-b386-c5f48c9c044a)
Есть проблема с отображением картинки, иногда картинка отображается хорошо, а они вылетает эта ошибка

2024-08-15 11:35 UTC, Chamber6821 commented
В ошибке написано, что домена нету в списке доменов, которым стоит доверять

2024-08-15 11:36 UTC, vladvg8 commented
А есть список доменов разрешенных?

2024-08-15 11:36 UTC, Chamber6821 commented
И написано в каком конфиге это исправить. Я уже добавлял туда Bubble, по образу и подобию сделай. Там работают шаблоны со звездочками

2024-08-18 09:53 UTC, closed without merging