pointCoutner added
Chamber6821/berega-map pull request #56
Opened 2024-09-09 07:14 UTC by vladvg8

2024-09-09 11:00 UTC, Chamber6821 commented on app/api/openApi.ts
Отступы 2 пробела

2024-09-09 11:02 UTC, Chamber6821 commented on app/api/BregaBuildingsInitializator.tsx
Этот файл нужен был для обработки объектов на стороне сервера

2024-09-09 11:05 UTC, Chamber6821 commented on app/api/openApi.ts
> +        let houseStatus = '';
`let` не должно быть. Лучше вынести код с `filters.groups.included(...)` в отдельную функцию

2024-09-09 11:08 UTC, Chamber6821 commented on app/api/openApi.ts
> +export async function fetchPointsCounter(
Функции должна описана через стрелочную анонимную функцию

2024-09-09 11:08 UTC, Chamber6821 commented on app/api/openApi.ts
> +export async function fetchFilteredPoints(
Функции должна описана через стрелочную анонимную функцию

2024-09-09 11:08 UTC, Chamber6821 commented on app/api/openApi.ts
> +export async function fetchBuildingById(id : string) : Promise<BuildingTypeOpenApi> {
Функции должна описана через стрелочную анонимную функцию

2024-09-09 11:10 UTC, Chamber6821 commented on app/api/openApi.ts
> +    return response.json();
Заинлайни константу `response`. Ее наличие не добавляет читаемости

2024-09-09 11:10 UTC, Chamber6821 commented on app/api/openApi.ts
> +    return await convertBuilding(buildingFromOpenApi);
Заинлайни константу `buildingFromOpenApi`. Ее наличие не добавляет читаемости

2024-09-09 11:11 UTC, Chamber6821 commented on app/filters/FilterApi.tsx
Отступы 2 пробела

2024-09-09 11:13 UTC, Chamber6821 commented on app/filters/FiltersHeader.tsx
> +import {FilterGroup, FilterGroups, FilterRooms, Range, useFilters} from "./useFilters"
Украл пробелы

2024-09-09 11:13 UTC, Chamber6821 commented on app/filters/FiltersHeader.tsx
> +
Лишняя пустая строка

2024-09-09 11:13 UTC, Chamber6821 commented on app/filters/FiltersHeader.tsx
> +
Лишняя пустая строка

2024-09-09 11:16 UTC, Chamber6821 commented on app/filters/FiltersHeader.tsx
Этот файл не относится к твоему PR. Верни его в исходное состояние

2024-09-09 11:16 UTC, Chamber6821 commented on app/filters/FiltersPopup.tsx
Этот файл не относится к твоему PR. Верни его в исходное состояние, несмотря на наличие бага

2024-09-09 11:20 UTC, Chamber6821 commented on app/map/Map.tsx
Твой PR основан на старой версии кода

2024-09-09 11:21 UTC, Chamber6821 commented on app/page.tsx
Твой PR основан на старой версии кода. Ты удалил обработку объектов на стороне сервера

2024-09-09 11:22 UTC, Chamber6821 commented
Впредь отправляй маленькие PR, размером до 100 новых строк. Новые большие PR я буду отбрасывать

2024-09-09 11:45 UTC, Chamber6821 commented on app/Cards.tsx
> +  const loadInitialItems = async () => {
Либо вынести в кастомный хук, который будет выглядеть как Zustand storage, но будет локальным для компонента

2024-09-09 12:01 UTC, Chamber6821 commented
Если возникают пэарзитектурные трудности при разбиении на маленькие PR, лучше создать Issue с описанием проблемы

2024-09-09 15:21 UTC, vladvg8 commented on next.config.mjs
> +      },
Нужно для того, чтоб я мог переходить по другим ссылкам или подгрузить фото со стороннего сайта, вроде из-за этого пришлось использовать это

2024-09-09 15:25 UTC, vladvg8 commented on app/Content.tsx
> +        if(zoom < 11) {
Была проблема с отображением, из-за того, что пока я жду fetch'a, я мог изменить уже зум и у меня появляются фантомные объекты. Попробую исправить

2024-09-09 15:32 UTC, vladvg8 commented on app/Cards.tsx
> +  const lastCardRef = useRef<HTMLDivElement | null>(null);
C undefined такая же история как и с null, пришлось бы указывать IntersectionObserver | undefined, т.к. yarn build ругается 
Я оставил так как было, но убрал | null

2024-09-09 15:33 UTC, vladvg8 commented on app/Content.tsx
> +        if(zoom >= 11) {
Причина ниже

2024-09-09 15:33 UTC, vladvg8 commented on app/Content.tsx
> +        if (filters.api === 'Встроенное') {
Причина ниже

2024-09-09 15:56 UTC, Chamber6821 commented on next.config.mjs
> +      },
А. Там в данных с апишки ссылки на сторонние ресурсы?

2024-09-09 16:26 UTC, Chamber6821 commented
Отправляй сразу все изменения по всем замечаниям после ревью. Не жди, пока я отпишу по части исправленных замечаний

2024-09-09 19:33 UTC, Chamber6821 commented
Перенастрой у себя отступы. На все проекте всегда во всех случаях отступ - 2 пробела

2024-09-10 18:18 UTC, Chamber6821 commented
Глянь свой git diff и посмотри, что бы было как можно меньше изменений связанных со стилем (лишние или потертые пробелы или пустые строки). Часть таких мест я отметил

2024-09-10 19:58 UTC, vladvg8 commented
Требуется ли убирать пустые строки в местах, а-ля, такого:
`
if (feature.geometry.type === 'Point') {
            const coordinates = feature.geometry.coordinates;
            map.flyTo({
              center: [coordinates[0], coordinates[1]],
              zoom: 12,
              essential: true,
            });

            const zoom = map.getZoom();
            if (onZoomChange) {
              onZoomChange(zoom);
            }
          }
`
Я понимаю, что данные пустые строки тут находятся лишь для улучшения читаемости, как бы разделяем действия на группы. Убирать ли мне такое?

2024-09-10 20:25 UTC, vladvg8 commented
В этом pr я добавил\убрал лишние пробелы из всех строк и import.
Код в моем комментарии немного поехал, если первый пункт был про это. В целом я понял тебя, сейчас исправлю

2024-09-10 20:29 UTC, Chamber6821 commented
Но при этом, что бы не раздувать PR, не стоит переформатировать те участки кода, в которых ты не правишь функционал

2024-09-11 14:25 UTC, Chamber6821 requested changes

2024-09-11 14:25 UTC, Chamber6821 commented on app/api/BregaBuildingsInitializator.tsx
Верни в исходное состояние. Строку удалил в конце

2024-09-11 14:25 UTC, Chamber6821 commented on app/useBuildings.ts
> +}))
Реверт

2024-09-12 07:41 UTC, Chamber6821 requested changes

2024-09-12 08:00 UTC, Chamber6821 requested changes

2024-09-12 08:00 UTC, Chamber6821 commented on app/map/Map.tsx
> +    }
Вот это никуда не годится, if не должен так использоваться, нужно упростить их

https://dev.to/sylwiavargas/5-ways-to-refactor-if-else-statements-in-js-functions-208e

2024-09-12 08:00 UTC, Chamber6821 commented on app/map/Map.tsx
> +    }
Проверка избыточна

2024-09-12 08:00 UTC, Chamber6821 commented on app/map/Map.tsx
> +      onZoomChange && onZoomChange(zoom);
Хватит объявлять константы на право и на лево. Код должен считаться как единое выражение, константы нужны только если значение используется несколько раз. А в тех случаях когда выражение становится слишком громоздким и сложно читаемым, надо выносить его куски в функции

2024-09-12 08:00 UTC, Chamber6821 commented on app/map/Map.tsx
> +            }
Зачем здесь try catch? Ты и без него увидишь всю ошибку

2024-09-12 08:00 UTC, Chamber6821 commented on app/map/Map.tsx
> +    }
Ты не должен постоянно добавлять или удалять словами слои и источники. Ты должен в начале в одном месте их добавить и они существуют вместе с картой до ее кончины. Ты должен управлять только данными источника

2024-09-12 08:00 UTC, Chamber6821 commented on app/map/Map.tsx
> +      }
Все тоже самое как и для `onZoomChange` (ниже)

2024-09-12 16:04 UTC, Chamber6821 commented
@vladvg8 позови, когда внесешь все правки или остануться только правки с вопросами ко мне. Пиши что думаешь под каждым исправлением, например если не согласен или оно уже сделано. Хотелось бы, что бы у нас выстраивался диалог

2024-09-12 16:12 UTC, vladvg8 commented
Я исправил проблемы с if/else и вынес логику loadMoreItems из Cards в useBuildings.
Еще у меня вопрос: какие именно файлы отличаются, потому что я как смотрел, вроде все, так, как у тебя в репе, или я чего-то не нашел

2024-09-12 17:02 UTC, Chamber6821 commented
@vladvg8 по поводу правок. напиши под каждым исправлением в этом треде, что либо оно сделано, либо под вопросом, когда меняешь код, то многие правки перестают быть видны в общем дифе.
По поводу лишних изменений - посмотри на diff этого PR

2024-09-12 20:07 UTC, vladvg8 commented
Я отметил все комментарии, что исправил или добавил.
Проблемы с возвращением старых FilterPopup и FilterHeader. Github показывает, мол, они разные, но они одинаковые, не помню почему. git diff ничего не возвращает
@Chamber6821

2024-09-12 20:09 UTC, Chamber6821 commented
@vladvg8 пройдись, пожалуйста, с самого начала по всем правкам и отпиши в каждую, что исправил. Там есть какие-то усторевшие, какие-то нет, какие-то не выполненные до конца (а может и нет таких)

2024-09-13 05:53 UTC, Chamber6821 requested changes

2024-09-13 05:53 UTC, Chamber6821 commented on app/api/BregaBuildingsInitializator.tsx
> +}
Здесь ты удалил пустую строку в конце файла. Вполне вероятно, что git diff не показывает ее, но верни пожалуйста обратно

2024-09-13 05:53 UTC, Chamber6821 commented on app/filters/FiltersHeader.tsx
> +  border: 1px solid rgb(164, 170, 180);
Реверт

2024-09-13 05:53 UTC, Chamber6821 commented on app/filters/FiltersHeader.tsx
> +  }`
Реверт

2024-09-13 05:53 UTC, Chamber6821 commented on app/filters/FiltersHeader.tsx
> +                        { type: React.HTMLInputTypeAttribute, placeholder?: string, validator?: (value: string) => T | undefined }):
Реверт

2024-09-13 05:53 UTC, Chamber6821 commented on app/filters/FiltersHeader.tsx
> +}
Хз почему оно в дифе, но сделай так, что бы не было

2024-09-13 05:53 UTC, Chamber6821 commented on app/filters/FiltersPopup.tsx
> +  }
Реверт

2024-09-13 05:53 UTC, Chamber6821 commented on app/filters/FiltersPopup.tsx
> +                        { type: React.HTMLInputTypeAttribute, placeholder?: string, validator?: (value: string) => T | undefined }):
Реверт

2024-09-13 05:53 UTC, Chamber6821 commented on app/filters/FiltersPopup.tsx
> +}
Хз почему оно в дифе, но сделай так, что бы не было

2024-09-13 05:53 UTC, Chamber6821 commented on app/page.tsx
> +}
Хз почему оно в дифе, но сделай так, что бы не было. Попробуй использовать блокнот вместо IDE, что бы избежать авто форматирования и вот гайд как откатить файл к определенному комиту

https://www.freecodecamp.org/news/git-revert-file-reverting-a-file-to-a-previous-commit/

2024-09-13 05:53 UTC, Chamber6821 commented on app/useBuildings.ts
> +  };
Не думаю, что let хорошая идея. Почему бы не брать количество построек и точек из данных стора или аргументов (не надо добавлять новые аргументы в обработчик)? Почему бы вместо передачи конкретных точек в обработчик не передавать фильтры для точек и что бы обработчик сам решил сколько каких точек подгрузить?

2024-09-13 05:53 UTC, Chamber6821 commented on app/map/Map.tsx
> +    };
Ты все ещё доьавляешь и удалчешь слои и ресурсы. Посмотри как организована работа с другими аналогичными слоями и ресурсами

[Инициализация](https://github.com/Chamber6821/berega-map/blob/6d2bc4a84fde73c3fd75ee5d797bc08c6507ece3/app/map/Map.tsx#L246)
[Обновление](https://github.com/Chamber6821/berega-map/blob/6d2bc4a84fde73c3fd75ee5d797bc08c6507ece3/app/map/Map.tsx#L347)

2024-09-13 05:56 UTC, Chamber6821 commented
@vladvg8 спасибо, что разобрался со старыми правками, вот новые

2024-09-13 06:05 UTC, Chamber6821 commented on app/useBuildings.ts
> +  };
Либо сделать 2 обработчика:
- `loadPoints(filters)` - обновляет фильтры внутри стора и мб загружает первую пачку точек
- `loadMorePoints()` - загружает следующую пачку точек

2024-09-13 13:09 UTC, Chamber6821 commented
@vladvg8 реализуй новые сторы в `app/storages` и перепиши `Content` с использованием этих сторов

2024-09-14 14:00 UTC, Chamber6821 commented
@vladvg8 я подумал, что не стоит переписывать Map по новому, на это уйдет слишком много времени. Лучше я сейчас подправлю его сам, я знаю что там нужно править

2024-09-15 07:50 UTC, Chamber6821 commented
@vladvg8 подключи пожалуйста `Card` в `Content`

2024-09-17 10:54 UTC, Chamber6821 commented
@vladvg8 че там с карточками? Сегодня бы до 19 хотелось, что бы они работали

2024-09-17 11:05 UTC, vladvg8 commented
Проблема с отображением Berega и Clusters.
Berega должны быть видны при любом зуме, сейчас они видны только если приблизить на 11 зум и выше.
Cluster должны быть видны, когда отдаляешься (зум < 11)
Points должны быть видны, когда приближаешь (зум >= 11)

2024-09-17 11:08 UTC, Chamber6821 commented
@vladvg8 так а в чем проблема сделать так как ты написал? Данные не правильно отдаются или что?

2024-09-17 11:09 UTC, vladvg8 commented
@Chamber6821 
Если ты про Cards, то они сделаны, проблемы только с отображением на карте

2024-09-17 11:12 UTC, Chamber6821 commented
@vladvg8 т.е. `useMarkers` отдает неверные данные, так?

2024-09-17 11:14 UTC, Chamber6821 approved these changes

2024-09-17 11:27 UTC, vladvg8 commented
Usemarkers отдает правильные данные, но на карте они отображаются неправильно, выше я написал в чем проблема

2024-09-17 11:30 UTC, Chamber6821 requested changes

2024-09-17 11:30 UTC, Chamber6821 commented on app/Content.tsx
> +      console.error("Ошибка при загрузке данных:", error);
Зачем ловить ты ловишь ошибку? Этим должна заниматься вызывающая оболочка, что она и делает. Исключение и так будет видно в логах, если его не поймать, а сетевую ошибку будет видно на вкладке Network

2024-09-17 11:30 UTC, Chamber6821 commented on app/Content.tsx
> +      console.error("Ошибка при загрузке данных:", error);
Если у этого кетча нет никакой мотивации, то удали его, если есть - то напиши ее здесь

2024-09-17 11:30 UTC, Chamber6821 commented on app/Content.tsx
> +  };
Лучше перенеси опеределение функции ДО ее использования (в строке 114)

2024-09-17 11:30 UTC, Chamber6821 commented on app/Content.tsx
> +        const newBuildings = await Promise.all(newBuildingIds.map(fetchBuilding));
Ты каждый раз по новой загружаешь данные, вместо использования кеша, как я тебе говорил

2024-09-17 11:30 UTC, Chamber6821 commented on app/Content.tsx
> +  const loadMoreBuildings = useCallback(async () => {
Зачем здесь `useCallback`?

2024-09-17 11:30 UTC, Chamber6821 commented
@vladvg8 ты не написал почему так происходит, ты написал только как диагностировать проблему

2024-09-17 11:33 UTC, Chamber6821 commented on app/Content.tsx
> +    setIsLoading(false);
Ты вынес `setIsLoading(false)` из блока `finally`. Я не уверен, что теперь код будет работать корректно при возникновении ошибки. Подозреваю, что мы получим бесконечное зависание, т.к. `isLoading` навсегда останется в `true`

2024-09-17 12:38 UTC, Chamber6821 commented
@vladvg8 внеси, пожалуйста изменения, который я попросил

2024-09-17 17:44 UTC, vladvg8 commented
При нажатии на какой-то отдельный cluster не зумит до 11, чтоб показались points, и не делает fly в точек

2024-09-17 17:45 UTC, vladvg8 commented
Не работает клик по точек с последщим popup и перекрашиванием точки в оранжевый цвет

2024-09-17 18:12 UTC, Chamber6821 commented on app/Content.tsx
> +    if (!hasMore || isLoading || !origin.elements.length) return;
Лучше длинну явно сравнивать числом, а не пользоваться приведением к булу. Приведение к булу - это что-то вроде проверки "Существует ли это значение?", а длинна, очевидно, существует всегда и семантика тут другая

2024-09-17 18:12 UTC, Chamber6821 commented on app/Content.tsx
> +    if (origin.elements.length) {
Лучше длинну явно сравнивать числом, а не пользоваться приведением к булу. Приведение к булу - это что-то вроде проверки "Существует ли это значение?", а длинна, очевидно, существует всегда и семантика тут другая

2024-09-17 18:12 UTC, Chamber6821 commented on app/Content.tsx
> +              loadForPoint(point)
Ты же не дожидаешься загрузки от `loadForPoint`. Разве это будет корректно подгружать новые карточки?

2024-09-17 18:12 UTC, Chamber6821 commented on app/Content.tsx
> +    setIsLoading(false);
Я думаю у тебя изначально правильно `setIsLoading(false)` был в блоке `finally` и сомневаюсь, что без `finally` флаг изменится корректно в случае возникновения ошибки

2024-09-17 18:58 UTC, Chamber6821 commented on app/Content.tsx
> +          }
Уже обновил `useBuildingMap`, что бы можно было сделать вторым способом

2024-09-17 18:58 UTC, Chamber6821 commented on app/Content.tsx
> +    }
Господи, да напиши ты уже

```ts
try {
  const newBuildings = await fetchMoreBuildings(buildings.length);
  setBuildings((prevBuildings) => [...prevBuildings, ...newBuildings]);
  const newOffset = buildings.length + newBuildings.length;
  setHasMore(newOffset < origin.elements.length);
} finally {
  setIsLoading(false);
}
```

2024-09-17 19:55 UTC, Chamber6821 commented on app/Content.tsx
> +        );
Сделай сразу возврат результата, без промежуточной константы

2024-09-17 20:17 UTC, Chamber6821 commented
@vladvg8 заебок. Теперь надо реализовать `handleMarkerSelected`

2024-09-17 20:23 UTC, vladvg8 commented
Я уже делаю

2024-09-17 22:08 UTC, vladvg8 commented
Костыль ужасный, origin.type замыкается на Berega и не изменяется, попытался через useCallback развязать, но не получилось
Теперь хотя бы нормально работает popup

2024-09-17 22:09 UTC, vladvg8 commented
Изменил также forPoint в useBuildingMap, сделал чтоб передался только id, чтоб адекватно забирать Building из map в useBuildingMap

2024-09-17 22:09 UTC, vladvg8 commented
Не получается сделать flyTo к точке, нужно как-то из Map забирать mapRef

2024-09-17 22:11 UTC, vladvg8 commented
Не работает изменение цвета маркера при изменении selectedMarker

2024-09-17 22:16 UTC, vladvg8 commented
@Chamber6821 
handleMarkerSelected сейчас пока что самый огромный костыль, если ты найдешь решение до 11:00, тогда измени, пожалуйста, пока что висят другие проблемы, а именно с flyTo vи покраской точек, реши пожалуйста как сможешь

2024-09-17 22:23 UTC, Chamber6821 commented
@Chamber6821

- `origin.type` не обновляется: я думаю, это проблема на стороне `Map`. Там просто не обновляется обработчик `onMarkerSelected`
- `flyTo`: там не нужен `useRef`, просто `Map` должен реагировать на изменения `center` как будто вызываетя `flyTo`. Если `flyTo` внутри оптимизирован для частых маленьких изменений, то все ок, а если нет, то могут возникнуть проблемы с производительностью и их я уже знаю как решить, но пока не стоит об этом заботится
- покраска точек: думаю проблема аналогична проблеме с `origin.type`

Чем из этого ты займешься?

2024-09-18 04:14 UTC, vladvg8 commented
@Chamber6821 
Я сделаю flyTo, сделай тогда покраску пожалуйста

2024-09-18 04:30 UTC, vladvg8 commented
Изменение mapCenter и zoom дает результат, однако пользователю ничего не видно, карта не двигается, просто у него сразу появляются точки

2024-09-18 05:23 UTC, vladvg8 commented
Изменение zoom'a через setZoom влечет за собой активацию flyTo по зуму, но если обрабатывать так же и mapCenter, получается проблема с тем, что невозможно даже карту подвинуть

2024-09-18 09:33 UTC, Chamber6821 commented
@vladvg8 я вроде все исправил

2024-09-18 09:46 UTC, merged