Loading element
Chamber6821/berega-map pull request #62
Opened 2024-09-21 11:35 UTC by vladvg8

2024-09-21 11:45 UTC, Chamber6821 commented
Оформи все решаемые проблемы в виде нескольких Issue и укажи, что исправляет их в описании PR через "Fixes #issue-numbet". Без Issue PR принят не будет

2024-09-22 21:51 UTC, Chamber6821 requested changes

2024-09-22 21:51 UTC, Chamber6821 commented on app/Content.tsx
> +  const { markers, origin , isLoadingFilters } = useMarkers(zoom, mapCenter);
Лучше просто `loading`, без filters и is

2024-09-23 08:05 UTC, Chamber6821 commented on app/filters/FiltersHeader.tsx
> +  }, [...price, ...area, ...rooms, ...types, types.length, agriculturals.length])
@vladvg8

2024-09-23 08:05 UTC, Chamber6821 commented on app/Content.tsx
> +  const { markers, origin , isLoadingFilters } = useMarkers(zoom, mapCenter);
@vladvg8

2024-09-23 08:17 UTC, Chamber6821 commented on app/filters/FiltersHeader.tsx
> +              onClick={() => handleSelect(x)}
Лучше перепиши с использованием `useEffect` в `FilterPopup` подобно [этому](https://github.com/Chamber6821/berega-map/blob/3319a95bf40af8daa547a856b8a22a9bda5300be/app/filters/FiltersPopup.tsx#L181)

2024-09-23 12:08 UTC, vladvg8 commented on app/filters/FiltersPopup.tsx
> +  };
Нет, первый вариант позволяет выбрать только один вариант, а второй позволяет выбирать несколько

2024-09-23 12:08 UTC, vladvg8 commented on app/filters/FiltersHeader.tsx
> +  }, [...price, ...area, ...rooms, ...types, types.length, agriculturals.length])
Проблема в том, что при выборе, допустим, варианта 3, а потом 4, ничего не произойдет, фильтр не применится, потому что срабатывает на длину фильтра, а она не изменится, как была 1, так и останется 1

2024-09-23 12:10 UTC, vladvg8 commented on app/filters/FiltersHeader.tsx
> +              onClick={() => handleSelect(x)}
Нужно чтоб использовать выбор одного элемента, стандартная реализация с `setSelected(selected.filter(y => y !== x))` позволит выбирать несколько элементов, а так это поведение контролирует handleSelect

2024-09-23 12:12 UTC, vladvg8 commented on app/Content.tsx
> +  const { markers, origin , isLoadingFilters } = useMarkers(zoom, mapCenter);
Done

2024-09-23 12:55 UTC, vladvg8 commented on app/filters/FiltersHeader.tsx
> +              onClick={() => handleSelect(x)}
Предложение в issue - #67

2024-09-23 13:38 UTC, vladvg8 commented on app/filters/FiltersPopup.tsx
> +
Done

2024-09-23 13:52 UTC, Chamber6821 requested changes

2024-09-23 13:52 UTC, Chamber6821 commented on app/filters/FiltersPopup.tsx
> +    flex-wrap: wrap;
Revert

2024-09-23 13:52 UTC, Chamber6821 commented on app/filters/FiltersPopup.tsx
> +        }
Revert

2024-09-23 13:52 UTC, Chamber6821 commented on app/filters/FiltersPopup.tsx
> +    font-weight: 500;
Revert

2024-09-23 13:52 UTC, Chamber6821 commented on app/filters/FiltersPopup.tsx
> +                        { type: React.HTMLInputTypeAttribute, placeholder?: string, validator?: (value: string) => T | undefined }):
Revert

2024-09-23 13:52 UTC, Chamber6821 commented on app/filters/FiltersPopup.tsx
> +  useEffect(() => { api === 'Внешнее' && selected.length > 1 && setSelected(selected.splice(-1)) }, [selected, setSelected])
Этот `useEffect` должен быть в `FiltersPopup`, не стоит расширять функционал существующих маленьких модулей усложняя их

2024-09-23 13:52 UTC, Chamber6821 commented on app/filters/FiltersHeader.tsx
> +  }, [...price, ...area, ...rooms, ...types, types.length, agriculturals.length])
Все сработает, есть написать через `useEffect`, то все будет происходить. Revert

2024-09-23 15:51 UTC, vladvg8 commented on app/filters/FiltersPopup.tsx
> +    flex-wrap: wrap;
Done

2024-09-23 15:51 UTC, vladvg8 commented on app/filters/FiltersPopup.tsx
> +        }
Done

2024-09-23 15:51 UTC, vladvg8 commented on app/filters/FiltersPopup.tsx
> +    font-weight: 500;
Done

2024-09-23 15:51 UTC, vladvg8 commented on app/filters/FiltersPopup.tsx
> +                        { type: React.HTMLInputTypeAttribute, placeholder?: string, validator?: (value: string) => T | undefined }):
Done

2024-09-23 16:11 UTC, Chamber6821 commented on app/filters/FiltersPopup.tsx
> +  const resetAgricultures = group == 'Зем. участки'
Это зачем? Ровно обратное изменение было в #60. Похоже на случайное изменение

2024-09-23 16:25 UTC, vladvg8 commented on app/filters/FiltersPopup.tsx
> +  useEffect(() => { api === 'Внешнее' && selected.length > 1 && setSelected(selected.splice(-1)) }, [selected, setSelected])
Не понял, он же и так в нем, он и так в FilterPopup

2024-09-23 16:29 UTC, Chamber6821 commented on app/filters/FiltersPopup.tsx
> +  useEffect(() => { api === 'Внешнее' && selected.length > 1 && setSelected(selected.splice(-1)) }, [selected, setSelected])
А, понял, мы о разном говорим, я про компонент `FiltersPopup`, а ты видимо про файл. Я специально прокинул `selected` и `setSelected` наружу хука, что бы снаружи можно было кастомищировать поведение

2024-09-23 16:36 UTC, vladvg8 commented on app/filters/FiltersPopup.tsx
> +  useEffect(() => { api === 'Внешнее' && selected.length > 1 && setSelected(selected.splice(-1)) }, [selected, setSelected])
Done

2024-09-23 16:36 UTC, vladvg8 commented on app/filters/FiltersPopup.tsx
> +  const resetAgricultures = group == 'Зем. участки'
Done

2024-09-23 16:37 UTC, vladvg8 commented on app/filters/FiltersHeader.tsx
> +  }, [...price, ...area, ...rooms, ...types, types.length, agriculturals.length])
Done

2024-09-23 17:35 UTC, Chamber6821 commented on app/filters/FiltersPopup.tsx
> +  useEffect(() => { api === 'Внешнее' && selected.length > 1 && setSelected(selected.splice(-1)) }, [selected, setSelected])
Я вижу старый диф. Ты точно отправил изменения?

2024-09-23 17:38 UTC, Chamber6821 requested changes

2024-09-23 17:38 UTC, Chamber6821 commented on app/filters/FiltersHeader.tsx
> +          selected?.includes(x)
`selected` всегда не `null` и не `undefined`

2024-09-23 17:44 UTC, vladvg8 commented on app/filters/FiltersHeader.tsx
> +          selected?.includes(x)
Done

2024-09-23 19:06 UTC, vladvg8 commented on app/filters/FiltersHeader.tsx
> +  useEffect(() => { api === 'Внешнее' && selected.length > 1 && setSelected(selected.splice(-1)) }, [selected, setSelected])
Хорошо, как тогда сделать, изменять функционал FiltersPopup так, как был раньше, без useEffect'a?
Я понял, что для FiltersHeader можно использовать, тогда не понимаю почему я не использовать и для FiltersPopup? Или вводить вообще отдельный обработчик для этого?

2024-09-23 19:15 UTC, Chamber6821 commented on app/filters/FiltersHeader.tsx
> +  useEffect(() => { api === 'Внешнее' && selected.length > 1 && setSelected(selected.splice(-1)) }, [selected, setSelected])
Нужен все этот же `useEffect`, но не в этом месте. Он должен быть где-нибудь в [здесь](https://github.com/Chamber6821/berega-map/blob/3319a95bf40af8daa547a856b8a22a9bda5300be/app/filters/FiltersHeader.tsx#L243)

2024-09-23 19:17 UTC, Chamber6821 commented on app/filters/FiltersHeader.tsx
> +  useEffect(() => { api === 'Внешнее' && selected.length > 1 && setSelected(selected.splice(-1)) }, [selected, setSelected])
Нужно этот `useEffect` либо засунуть внутрь функции `FiltersHeader`, либо завернуть в отдельный хук поверх `useVariantInput`

2024-09-23 21:07 UTC, vladvg8 commented on app/filters/FiltersHeader.tsx
> +  useEffect(() => { api === 'Внешнее' && selected.length > 1 && setSelected(selected.splice(-1)) }, [selected, setSelected])
Done

2024-09-23 21:19 UTC, Chamber6821 commented on app/filters/FiltersPopup.tsx
> +  useEffect(() => { api === 'Внешнее' && selected.length > 1 && setSelected(selected.splice(-1)) }, [selected, setSelected])
@vladvg8 аналогично с `FiltersHeader`

2024-09-23 21:21 UTC, Chamber6821 commented
@vladvg8 осталось последнее исправление и можно мерджить

2024-09-23 21:24 UTC, vladvg8 commented on app/filters/FiltersPopup.tsx
> +  useEffect(() => { api === 'Внешнее' && selected.length > 1 && setSelected(selected.splice(-1)) }, [selected, setSelected])
Могу ли я использовать такой же подход как в FiltersHeader?

2024-09-23 21:25 UTC, Chamber6821 commented
Кажется я вижу бесконечную загрузку. Мб конечно у меня с интернетом, но в течении минуты загрузки, я не увидел никакого трафика

![Screenshot_2024-09-24-00-22-43-279_com.android.chrome.jpg](https://github.com/user-attachments/assets/1030bfc5-8ccb-4496-a5e4-ce24acd225d8)

2024-09-23 21:27 UTC, Chamber6821 commented on app/filters/FiltersPopup.tsx
> +  useEffect(() => { api === 'Внешнее' && selected.length > 1 && setSelected(selected.splice(-1)) }, [selected, setSelected])
Да, так и надо. В этом месте код дублируется, у меня не достаточно познаний в реакте, что бы красиво это вынести в отдельную хуки и компоненты

2024-09-23 21:28 UTC, vladvg8 commented on app/filters/FiltersPopup.tsx
> +  useEffect(() => { api === 'Внешнее' && selected.length > 1 && setSelected(selected.splice(-1)) }, [selected, setSelected])
Done

2024-09-23 21:29 UTC, vladvg8 commented
Не делай мерж пока, тут проблема с отображением еще, одну минуту
Бесконечная загрузка потому api лежит

2024-09-24 04:30 UTC, vladvg8 commented
Все готово уже

2024-09-24 05:04 UTC, vladvg8 commented on app/filters/FiltersPopup.tsx
> +  useEffect(() => { api === 'Внешнее' && selected.length > 1 && setSelected(selected.splice(-1)) }, [selected, setSelected])
Done

2024-09-24 05:44 UTC, Chamber6821 commented on app/filters/FiltersPopup.tsx
> +  useEffect(() => { api === 'Внешнее' && selected.length > 1 && setSelected(selected.splice(-1)) }, [selected, setSelected])
Ты добавил новый хук, но не вернул в исходное состояние старый

2024-09-24 05:47 UTC, Chamber6821 commented
@vladvg8 скинь пример ручки API, которое не отвечает. Нужно, что бы к Илье обратится

2024-09-24 06:21 UTC, vladvg8 commented
Вся фильтрация отвалилась, ничего не работает

2024-09-28 08:24 UTC, closed without merging

2024-09-28 12:55 UTC, Chamber6821 commented
@vladvg8 зачем ты закрыл PR?

2024-09-30 09:10 UTC, Chamber6821 commented
@vladvg8